// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0-GcgzrH1RMRnlxTdDG1Q5dN8_ZYYzIc',
    appId: '1:162782169027:android:b02a34860710534e029f76',
    messagingSenderId: '162782169027',
    projectId: 'projectb-ef9eb',
    storageBucket: 'projectb-ef9eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD58n03fiV7osGladR77medKMUATEbdoLY',
    appId: '1:162782169027:ios:90c3bb5da44f1afe029f76',
    messagingSenderId: '162782169027',
    projectId: 'projectb-ef9eb',
    storageBucket: 'projectb-ef9eb.appspot.com',
    androidClientId: '162782169027-3nfimf83mggqelk9js4j9r9q8q1u9ga6.apps.googleusercontent.com',
    iosClientId: '162782169027-p1rblb6go6mmjqnups5it4kltp73qk9n.apps.googleusercontent.com',
    iosBundleId: 'io.github.bulletsentence.projectb',
  );
}
